spring:
  datasource:
    url: jdbc:mysql://soft-tickets.c1mgk0ygq54m.us-east-1.rds.amazonaws.com:3306/DigiTicket?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: jv.Q58a-d.AVh+5
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # en desarrollo: update | en producción real: validate o none
    show-sql: true       # muestra los queries en consola
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
